jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
    - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          name: "admin"
          properties:
            - "apiToken"
            - "myView"
            - "timezone"
            - "mailer"
            - preferredProvider:
                providerId: "default"
        - id: "chocolateen"
          name: "Hugo"
          properties:
            - "apiToken"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - "timezone"
              password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "vaugie_g"
            name: "Garance"
            properties:
              - "apiToken"
              - "myView"
              - preferredProvider:
                  providerId: "default"
              - "timezone"
                password: ${USER_VAUGIE_G_PASSWORD}
        - id: "i_dont_know"
            name: "Jeremy"
            properties:
              - "apiToken"
              - "myView"
              - preferredProvider:
                  providerId: "default"
              - "timezone"
                password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
            name: "Nassim"
            properties:
              - "apiToken"
              - "myView"
              - preferredProvider:
                  providerId: "default"
              - "timezone"
                password: ${USER_NASSO_PASSWORD}
  slaveAgentPort: 50000
  systemMessage: "Welcome to the Chocolatine-PoweredMarvin Jenkins Instance."
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpPassword: "{AQAAABAAAAAQDWsBcpaoZwEzYdEBI4v4EnMnIiwSumHO9wSu/AotfZk=}"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "Adresse pas encore configurée <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      job('Daily Dose of Satisfaction') {
        steps {
          shell('echo "Hello dear $NAME!"')
          shell('date')
          shell('echo "This is your DDoS number $BUILD_NUMBER."')
        }
      }