jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permission:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permission:
              - "Job/Build"
              - "Job/Workspace"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permission:
              - "Job/Build"
              - "Job/Read"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Configure"
              - "Job/Move"
            assignement:
              - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permission:
              - "Job/Read"
              - "Job/Workspace"
            assignement:
              - "nasso"
jobs:
  - script: >
      job('Daily Dose of Satisfaction') {
        steps {
          shell('echo "Hello dear $NAME!"')
          shell('date')
          shell('echo "This is your DDoS number $BUILD_NUMBER."')
        }
      }